### ISSUE TITLE
Mapping path and method not clear

### ISSUE THREAD

**Issue by mpreusse** [icb-knowing/biomapr#6]
- Are there any insights into how the mapping actually happened (further looking into the “distance” value)?

- Interface (5): Mir ist nur so ungefähr klar was das distance bedeutet. Ohne das dahinter stehende Schema zu kennen ist es schwierig das zu interpretieren. Was mich als Nutzer ja eigentlich interessiert ist nur ob das das gleiche gen ist und die beide IDs synonym zu verwenden sind. Es scheint dass das bei distance=2 der Fall ist und bei distance>2 nicht. Aber was genau dann die Beziehung zwischen den IDs bei distance > 2 ist ist mir nicht klar. 

- verschiedene Versionen: Das ist bei diesen Mappings eines der Hauptprobleme, denke ich. Z.b. CPAMD9 wurde umbenannt in A2ML1. Wenn ich mit map die Symbole zur zugehörigen ENSEMBL id ENSG00000166535 abfrage bekomme ich beide Symbole zurück. Ohne zusätzliche Informationen kann ich aber nicht entscheiden welches der aktuelle Name ist (den ich dann z.B in das per schreiben würde).

**Comment by sankleta** [comment]
we return mapping paths now
